services:
  db:
    image: mysql:8
    restart: always
    container_name: market_etl
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql #데이터 보존용
      - ./SQL/table_sql.sql:/docker-entrypoint-initdb.d/table_sql.sql:ro #sql 경로 : 컨테이너 쪽에서의 경로

  airflow:
    image: apache/airflow:3.3.0

volumes:
  dbdata:
