CREATE TABLE IF NOT EXISTS Market_Ticket(
    market varchar(100),
    slot_at datetime, #데이터가 속한 슬롯, 키
    collected_at datetime, #api를 호출한 시점
    trade_date date,
    trade_time time,
    trade_date_kst date,
    trade_time_kst time,
    trade_timestamp BIGINT,
    opening_price DECIMAL(30,10),
    high_price DECIMAL(30,10),
    low_price DECIMAL(30,10),
    trade_price DECIMAL(30,10),
    prev_closing_price DECIMAL(30,10),
    changer varchar(100),
    change_price DECIMAL(30,10),
    change_rate DECIMAL(30,10),
    signed_change_price DECIMAL(30,10),
    signed_change_rate DECIMAL(30,10),
    trade_volume DECIMAL(30,10),
    acc_trade_price decimal(40,10),
    acc_trade_price_24h decimal(40,10),
    acc_trade_volume decimal(40,10),
    acc_trade_volume_24h decimal(40,10),
    highest_52_week_price DECIMAL(30,10),
    highest_52_week_date date,
    lowest_52_week_price DECIMAL(30,10),
    lowest_52_week_date date,
    time_stamp BIGINT,
    constraint uq_market_time UNIQUE(market,slot_at)
);